name: group9_airbnb_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - folium=0.16.*
  - ipykernel=6.24.0
  - jupyterlab=4.1.*
  - matplotlib=3.8.*
  - nb_conda_kernels
  - nbconvert=7.16.2
  - numpy=1.25.*
  - pandas=1.3.*
  - pip>=23.2.1
  - plotly=5.20.*
  - python=3.10
  - quarto
  - requests=2.31.0
  - scikit-learn=0.24.*
  - scipy>=1.11.0
  - seaborn=0.13.*